set_property SRC_FILE_INFO {cfile:D:/homework_space/FPGA/CPU8bit/cpu/cpu.srcs/constrs_1/new/navigator.xdc rfile:../../../cpu.srcs/constrs_1/new/navigator.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports sys_clk]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports sys_rstn]
